name: emi_calculator
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  injectable: ^2.3.2
  get_it: ^7.6.4
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  firebase_crashlytics: ^3.4.9
  firebase_core: ^2.24.2
  flutter_screenutil: ^5.9.0
  stack_trace: ^1.11.1
  reactive_forms: ^16.1.1
  reactive_forms_annotations: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  injectable_generator: ^2.4.0
  flutter_gen_runner: ^5.3.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  reactive_forms_generator: ^4.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
flutter_gen:
  output: lib/generated
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true

  assets:
    enabled: true